global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'laravel_app'
    static_configs:
      - targets: ['suivie-api:80']
    metrics_path: '/metrics'

  - job_name: 'mysql'
    static_configs:
      - targets: ['laravel-academic-DB:3306']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']